### ISSUE TITLE
Copy lensert on first launch

### ISSUE THREAD

**Issue by joelluijmes** [zwolsman/lensert-win#24]
when opening directly from zip you'll get this:
![Image](https://lensert.com/ByQiQLpm)

Issue: when clearing the temp the link probably still exist and on windows logon you'll get invalid link error.

**Comment by zwolsman** [comment]
This is because this isn't a signed executable. You'll need to sign it with signtool and a valid .pfx key file. I don't have one since it's expensive. Cheapest one I found is [here](https://www.leaderssl.nl/suppliers/comodo/products/code_signing?gclid=CjwKEAjwsr-6BRCLvrj785rbhTsSJADjUxakpcIiUKy-iLRib8qo5jWWqguY2EaAO9uavHw2Reer8RoCBwHw_wcB)

**Comment by joelluijmes** [comment]
True but that isn't the issue at hand ;)
